version: "3.8"
services:
    web:
        container_name: ci-web
        build: 
            context: ./php
            dockerfile: Dockerfile
        volumes:
            -   ../server:/var/www/html/app/
        ports:
            -   "80:80"
        depends_on:
            -   db
    db:
        image: mariadb
        restart: always
        volumes:
            -   ../mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        ports:
            -   "3306:3306"
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            -   "8080:80"
        environment:
            -   PMA_ARBITRARY=1